server:
  port: 9080
spring:
  datasource:
    name: union
    url: jdbc:mysql://127.0.0.1:3306/dnf_union?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最大链接数
      maximum-pool-size: 30
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 10000
      # 最小空闲链接数
      minimum-idle: 5
      #允许连接在连接池中空闲的最长时间
      idle-timeout: 600000
      # 新建链接是判断
      connection-init-sql: SELECT 1

logging:
  level:
    root: INFO
    com:
      tx:
        union: debug
      ibatis: debug
    org:
      springframework:
        web: DEBUG
        jdbc: DEBUG


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: com.tx.union.pojo.entity
  configuration:
    # 数据库表与实体类的驼峰命名自动转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_



